baseURL = "http://example.org/"
languageCode = "en-us"
title = "Divertise Asia"
theme = "divertise"

[Author]
  name = "Divertise Asia Co., Ltd."
  email = "contact@divertise.asia"
  facebook = "DivertiseAsia"
  linkedin = "divertiseasia"
  github = "DivertiseAsia"
